/*新建数据库*/
CREATE DATABASE IF NOT EXISTS sy DEFAULT CHARSET utf8;

/*新建表*/
--COLLATE utf8_general_ci;
--CREATE TABLE `t_user` (
--  `USER_ID` INT(11) NOT NULL AUTO_INCREMENT,
--  `USER_NAME` CHAR(30) NOT NULL,
--  `USER_PASSWORD` CHAR(10) NOT NULL,
--  PRIMARY KEY (`USER_ID`),
--  KEY `IDX_NAME` (`USER_NAME`)
--) ENGINE=INNODB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8;

CREATE TABLE t_user (
	USER_ID INT NOT NULL,
	USER_NAME VARCHAR(45),
	USER_PASSWORD VARCHAR(45),
	PRIMARY KEY (USER_ID)
) 
/*插入测试数据*/
INSERT INTO t_user (USER_ID, USER_NAME, USER_PASSWORD) VALUES (1, '张三', '123456');
INSERT INTO t_user (USER_ID, USER_NAME, USER_PASSWORD) VALUES (2, '李四', '123456');